Update README.md
RPSTD/component101 pull request #94
Opened 2023-10-07 06:20 UTC by Redox1223

updated 
1, Introduction to light sensors 
2, what are light sensors used for 
3, output analog
4, new theory facts

2023-10-07 09:38 UTC, sasankaweera123 requested changes

2023-10-07 09:38 UTC, sasankaweera123 commented on LightSensor/README.md
> +# C0001-Light Sensor:
Remove the ":" mark

2023-10-08 10:03 UTC, Redox1223 commented on LightSensor/README.md
> +# C0001-Light Sensor:
ok

2023-10-14 05:05 UTC, sasankaweera123 approved these changes

2023-10-28 09:44 UTC, merged